apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world-deployment
spec:
  replicas: 1  # Number of replicas/instances you want to run
  selector:
    matchLabels:
      app: java-hello-world
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      containers:
      - name: java-hello-world
        image: ashish233001/java-Hello-World # Your Docker image
        ports:
        - containerPort: 8080 # Port your Java app is listening on
